version: '3'
services:
  csv2rdf:
    image: node:11.9.0
    working_dir: "/var/www/app/csv2rdf"
    environment:
      - BASE_URL=https://prismdb.takanakahiko.me
    volumes:
      - .:/var/www/app
    command: bash -c "npm i && npm run start"