on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v1
      - working-directory: csv2rdf
        run: | 
          npm ci
          BASE_URL=https://prismdb.takanakahiko.me npm start
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'
      - uses: actions/upload-artifact@master
        with:
          name: rdfs
          path: virtuoso/data/toLoad/
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@master
        with:
          name: rdfs
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'
      - run: |
          RDFLINT_VERSION=0.0.9
          wget -q https://jitpack.io/com/github/imas/rdflint/$RDFLINT_VERSION/rdflint-$RDFLINT_VERSION-all.jar
          java -jar rdflint-$RDFLINT_VERSION-all.jar -config .circleci/rdflint-config.yml -targetdir rdfs
  download-s3:
    runs-on: ubuntu-latest
    steps:
      - run: curl -OL https://prismdb-build-results.s3-ap-northeast-1.amazonaws.com/${{ github.event.pull_request.base.sha }}.ttl
      - run: mv ${{ github.event.pull_request.base.sha }}.ttl base.ttl
      - uses: actions/upload-artifact@master
        with:
          name: base
          path: base.ttl
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.6.0
        with:
          id: hoge
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const huga = 'hugo';
            console.log(`test`);
            console.log(`::set-output name=huga::${huga}`);
      - run: echo ${{ steps.hoge.huga }}
  download-master-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -v -L -o test.zip -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/prickathon/prismdb/actions/artifacts/2092935/zip"
      - run: unzip test.zip
      - run: ls
      - run: ls test
  check:
    needs: [build, download-s3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@master
        with:
          name: rdfs
      - uses: actions/download-artifact@master
        with:
          name: base
      - run: ./scripts/GetDiffs.sh
      - uses: actions/upload-artifact@master
        with:
          name: diff
          path: ./diff.md

